name: Logs and saves report as an artifact

on:
  workflow_call:
    inputs:
      triggered_by:
        required: true
        type: string

jobs:
  log-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate log
        run: |
             echo "===Artifact logs===" > log.txt
             echo "Triggered by: ${{inputs.triggered_by}}" >> log.txt
             echo "Date: $(date -u)" >> log.txt
             echo "Commit: $GITHUB_SHA" >> log.txt
             echo "Commit message: ${{git log -1 --pretty=%B}}" >> log.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: reusable log
          path: log.txt
