name: Node CI

on:
	push:
		branches: [master]
	
jobs:
	show-text:
		runs-on: ubuntu-latest

	steps:
		name: Checkout Repo
		uses: action/checkout@v4

		name: Print content of notes.txt
		run: echo notes.txt
