name: Show Text CI

on:
  push:
    paths:
      - notes.txt
    branches: [master]

jobs:
  show-text:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Print content of notes.txt
        run: cat notes.txt

      - name: Print the current time and date
        run: date
